// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd9VP1S2BZzTAQE-Q4PoC-7IDtcP7wDyY',
    appId: '1:1080676928394:web:26f0b85ddb772e2a595673',
    messagingSenderId: '1080676928394',
    projectId: 'kgftraining-bed80',
    authDomain: 'kgftraining-bed80.firebaseapp.com',
    storageBucket: 'kgftraining-bed80.appspot.com',
    measurementId: 'G-T1BPMRX8ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDawxiCABy-t9PABjV5SFSElnlb85_3tlo',
    appId: '1:1080676928394:android:647ce2479574f3ba595673',
    messagingSenderId: '1080676928394',
    projectId: 'kgftraining-bed80',
    storageBucket: 'kgftraining-bed80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRRWRdeX_MTzwpPGmyY4xDtWeAenFpmpQ',
    appId: '1:1080676928394:ios:64a3f014b5429fa3595673',
    messagingSenderId: '1080676928394',
    projectId: 'kgftraining-bed80',
    storageBucket: 'kgftraining-bed80.appspot.com',
    androidClientId: '1080676928394-5kbmopn4kdkjsud2jkbhai4c3khht27e.apps.googleusercontent.com',
    iosClientId: '1080676928394-kl4q3b8londf95tosf4fagmdvj5dekto.apps.googleusercontent.com',
    iosBundleId: 'com.example.kgfApp',
  );
}
